# Generated by Django 3.2.6 on 2021-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0002_megamillions_winningnumberscombination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megamillions',
            name='draw_date',
            field=models.DateField(),
        ),
    ]
