# Generated by Django 3.2.6 on 2021-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0002_megamillions_winningnumberscombination'),
    ]

    operations = [
        migrations.AddField(
            model_name='winningnumberscombination',
            name='number_of_draws',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winningnumberscombination',
            name='possibility',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
