# Generated by Django 3.2.6 on 2021-08-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0003_alter_megamillions_draw_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megamillions',
            name='draw_date',
            field=models.DateTimeField(),
        ),
    ]
