# Generated by Django 3.2.6 on 2021-08-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0003_auto_20210817_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningnumberscombination',
            name='possibility',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
