# Generated by Django 3.2.6 on 2021-08-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0007_auto_20210817_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winningnumberscombination',
            name='possibility',
        ),
    ]
