# Generated by Django 3.2.6 on 2021-08-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0010_auto_20210817_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningnumberscombination',
            name='possibility',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
