# Generated by Django 3.2.6 on 2021-08-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0012_alter_winningnumberscombination_possibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='winningnumberscombination',
            name='top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
