# Generated by Django 3.2.6 on 2021-08-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0013_winningnumberscombination_top_pick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winningnumberscombination',
            old_name='top_pick',
            new_name='quick_pick',
        ),
    ]
