# Generated by Django 3.2.6 on 2021-08-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0014_rename_top_pick_winningnumberscombination_quick_pick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winningnumberscombination',
            old_name='quick_pick',
            new_name='top_occurrence',
        ),
    ]
