# Generated by Django 3.2.6 on 2021-08-21 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0015_rename_quick_pick_winningnumberscombination_top_occurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powerball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateTimeField()),
                ('winning_numbers', models.CharField(max_length=20)),
                ('power_ball', models.CharField(max_length=3)),
                ('multiplier', models.CharField(blank=True, max_length=3, null=True)),
                ('number_of_draws', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='winningnumberscombination',
            name='game',
            field=models.CharField(choices=[('MEGAMILLIONS', 'MEGAMILLIONS'), ('POWERBALL', 'POWERBALL')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
