# Generated by Django 3.2.6 on 2021-08-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0016_auto_20210821_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='megamillions',
            old_name='mega_ball',
            new_name='ball',
        ),
        migrations.RenameField(
            model_name='powerball',
            old_name='power_ball',
            new_name='ball',
        ),
    ]
