# Generated by Django 3.2.6 on 2021-08-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamillions', '0017_auto_20210821_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningnumberscombination',
            name='winning_numbers_combination',
            field=models.CharField(max_length=50),
        ),
    ]
