# Generated by Django 3.2.6 on 2021-08-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMillions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateTimeField()),
                ('winning_numbers', models.CharField(max_length=20)),
                ('ball', models.CharField(max_length=3)),
                ('multiplier', models.CharField(blank=True, max_length=3, null=True)),
                ('number_of_draws', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Powerball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateTimeField()),
                ('winning_numbers', models.CharField(max_length=20)),
                ('ball', models.CharField(max_length=3)),
                ('multiplier', models.CharField(blank=True, max_length=3, null=True)),
                ('number_of_draws', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WinningNumbersCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('MEGAMILLIONS', 'MEGAMILLIONS'), ('POWERBALL', 'POWERBALL')], max_length=50)),
                ('winning_numbers_combination', models.CharField(max_length=50)),
                ('winning_numbers_combination_occurrence', models.IntegerField()),
                ('number_of_draws', models.IntegerField()),
                ('possibility', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top_occurrence', models.BooleanField(default=False)),
            ],
        ),
    ]
