# Generated by Django 3.2.6 on 2021-08-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_megamillions_powerball_winningnumberscombination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningnumberscombination',
            name='game',
            field=models.CharField(choices=[('megamillions', 'megamillions'), ('powerball', 'powerball')], max_length=50),
        ),
    ]
